network_module: hymotion/network/hymotion_mmdit.HunyuanMotionMMDiT
network_module_args:
  apply_rope_to_single_branch: false
  ctxt_input_dim: 4096
  dropout: 0.0
  feat_dim: 1280
  input_dim: 201
  mask_mode: narrowband
  mlp_ratio: 4.0
  num_heads: 20
  num_layers: 27
  time_factor: 1000.0
  vtxt_input_dim: 768
train_pipeline: hymotion/pipeline/motion_diffusion.MotionFlowMatching
train_pipeline_args:
  enable_ctxt_null_feat: true
  enable_special_game_feat: true
  infer_noise_scheduler_cfg:
    validation_steps: 50
  losses_cfg:
    recons:
      name: SmoothL1Loss
      weight: 1.0
  noise_scheduler_cfg:
    method: euler
  output_mesh_fps: 30
  random_generator_on_gpu: false
  test_cfg:
    mean_std_dir: ./stats/
    text_guidance_scale: 5.0
  text_encoder_cfg:
    llm_type: qwen3
    max_length_llm: 128
  text_encoder_module: hymotion/network/text_encoders/text_encoder.HYTextModel
  train_cfg:
    cond_mask_prob: 0.1
  train_frames: 360
